name: Smoke Tests
on: push
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Initial step
         run: exit 1
       - name: Check of atleast ONE of the previous steps failed
         if: ${{ failure() }}
         run: |
           echo "Run if any of the previous step of a this job fails!"
       - name: Explicitly check if atleast ONE of the previous steps failed
         if: ${{ github.action_status == 'failure' }}
         run: |
           echo "Run if any of the previous step of a this job fails!"
       - name: Check if NONE of the previous steps failed
         if: ${{ success() }}
         run: |
           echo "Run if NONE of the previous step of a this job fails!"