name: Smoke Tests
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  build:
     runs-on: ubuntu-latest
     needs: ci
     if: always()
     env:
       conclusion: $     
     steps:
       - run: |
          echo "Result = $conclusion"
          if [ ${conclusion} == "success" ]; then
              exit 0
          else
              exit 1
          fi