name: Smoke Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  deploy:
     runs-on: ubuntu-latest
     needs: 
       - build
     steps:
       - name: Atleast ONE of the previous steps failed
         if: ${{ failure() }}
         run: |
           echo "Run if any of the previous step of a this job fails!"
           exit 1
     steps:
       - name: NONE of the previous steps failed
         if: ${{ success() }}
         run: |
           echo "Run if NONE of the previous step of a this job fails!"
           exit 0