  name: Smoke Tests
  on: push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - run: exit 0
    deploy:
       runs-on: ubuntu-latest
       needs: 
         - build  
       if: ${{ failure() }}
       steps:
         - name: Run if ANY of the previous step of a this job fails!
           run: |
             echo "Dependent job failed!"
             exit 1
