name: Smoke Tests
on: push
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Initial step
         run: exit 0
       - name: Atleast ONE of the previous steps failed
         if: ${{ failure() }}
         run: |
           echo "Run if any of the previous step of a this job fails!"
           exit 1
       - name: NONE of the previous steps failed
         if: ${{ success() }}
         run: |
           echo "Run if NONE of the previous step of a this job fails!"
           exit 0