name: Smoke Tests
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: |

          exit $(( ( RANDOM % 2)  + 1 - 1 ))
  build:
     runs-on: ubuntu-latest
     needs: 
       - ci
     if: always()    
     steps:
       - name: Fail the job if result is not success
         if: ${{ needs.ci.result != 'success'}}
         run: | 
           echo "Dependent job failed!"
           exit 1
       - name: Run job if result is success
         run: |
           echo "Dependent job succeeded!"
            exit 0
