name: Smoke Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  deploy:
     runs-on: ubuntu-latest
     needs: 
       - build
     if: always()    
     steps:
       - name: Fail the job if result is not success
         if: ${{ needs.build.result != 'success'}}
         run: |
           echo "Dependent job failed!"
           exit 1
       - name: Run job if result is success
         run: |
           echo "Dependent job succeeded!"
            exit 0