name: Smoke Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit_status=$(( ( RANDOM % 2)  + 1 -1 ))
          echo "Exit status $exit_status"
          exit $exit_status
  deploy:
     runs-on: ubuntu-latest
     needs: 
       - build
     if: always()    
     steps:
       - name: The job has failed
         if: ${{ failure() }}
         run: |
           echo "Fails if any of the previous step of a job fails!"
           exit 1
       - name: Run job if result is success
         run: |
           echo "Dependent job succeeded!"
           exit 0

