  name: Smoke Tests
  on: push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - run: exit 1
    deploy:
       runs-on: ubuntu-latest
       needs: 
         - build
       if: always()    
       steps:
         - name: Run if ANY of the previous step of a this job fails!
           if: ${{ failure() }}
           run: |
             echo "Dependent job failed!"
             exit 1
         - name: Run if NONE of the previous step of a this job fails!
           run: |
             echo "Dependent job succeeded!"
              exit 0
