 name: Smoke Tests
 on: push
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random exit status 0 or 1
        run: |
          exit_status=$(( ( RANDOM % 2)  + 1 -1 ))
          echo "Exit status $exit_status"
          exit $exit_status
   deploy:
      runs-on: ubuntu-latest
      needs: 
        - build
      if: ${{ always() }}    
      steps:
        - name: Fail the job if result is not success
          if: ${{ needs.build.result != 'success'}}
          run: |
            echo "Dependent job failed!"
            exit 1
        - name: Run job if result is success
          run: |
            echo "Dependent job succeeded!"
             exit 0
