name: Smoke Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  deploy:
     runs-on: ubuntu-latest
     needs: 
       - build  
     steps:
       - name: The job has failed
         if: ${{ failure() }}
         run: |
           echo "Fails if any of the previous step of a job fails!"
           exit 1
