name: Smoke Tests
on: push
jobs:
  build_and_deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Run build step
         run: |
           echo "Running build"
           exit 0
       - name: Run deploy step
         run: |
           echo "Running deploy"
           exit 0   
       - name: The build job has failed
         if: ${{ failure() }}
         run: |
           echo "Fails if any of the previous step of a this fails!"
           exit 1
