name: Smoke Tests
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random exit status 0 or 1
        run: |
          echo "exit_status=$(( ( RANDOM % 2)  + 1 -1 ))" >> $GITHUB_ENV   
          echo "Exit status "${{ env.exit_status }}"
          exit "${{ env.exit_status }}"
  build:
     runs-on: ubuntu-latest
     needs: 
       - ci
     if: always()    
     steps:
       - name: Fail the job if result is not success
         if: ${{ needs.ci.result != 'success'}}
         run: |
           echo "Dependent job failed!"
           exit 1
       - name: Run job if result is success
         run: |
           echo "Dependent job succeeded!"
            exit 0