name: Smoke Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  deploy:
     runs-on: ubuntu-latest
     needs: 
       - build
     if: ${{ failure() }}
     steps:
       - name: One of the previous steps of this job failed
         run: |
           echo "Run if any of the previous step of a this job fails!"
           exit 1