name: Smoke Tests
on: push
jobs:
  build_and_deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Build
         run: |
           echo "Running build"
           exit 0
       - name: Deploy
         run: |
           echo "Running deploy"
           exit 1  
       - name: One of the jobs has failed
         if: ${{ failure() }}
         run: |
           echo "Fails if any of the previous step of a this fails!"
           exit 1
